[package]
name = "tiled-spider-oil-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde-xml-rs = "0.6.0"
thiserror = "1.0.64"
